export PATH="$HOME/.local/bin:$PATH"
set -o vi


alias build="./build.sh"
alias emacsd="emacs --daemon"
alias emacsc="emacsclient -c -a 'emacs'"
alias gap="git add -p"
alias gcp="git commit -p"
alias kpx="keepassxc-cli open"
alias ls="ls --color=auto"
alias ll="ls -l"
alias la="ls -lA"
alias new="source \$HOME/.bashrc"
alias newbar="pkill waybar; waybar &disown"
alias ping="ping -c 5"
alias vi="\vim"
alias vim="nvim"
alias ..="cd .."

fastfetch -c $HOME/.config/fastfetch/config.json
